# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"
linters:
  enable:
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - whitespace
formatters:
  enable:
    - gofmt
